### ISSUE TITLE
Can r8brain resample bidirectionally without slipping?

### ISSUE THREAD

**Issue by nadernader99** [avaneev/r8brain-free-src#12]
I have a real-time use case where I am adapting a 48KHz audio interface to 44.1Khz process that both records and plays audio simultaneously.

I am using the CDSPResampler24 in both directions, with buffers to handle the varying number of samples produced by each submitted buffer. I have a similar question on [stackoverflow](https://stackoverflow.com/questions/66102901/bi-directional-audio-resampling-algorithm-without-time-slippage-r8brain-et-al), but I am opening this issue specifically for r8brain.

Here is the flow of data through the process.

48K Input -> [48K to 44.1K] -> [buffer] -> process -> [44.1K to 48K] -> [buffer] -> 48K Output

The InLenBeforeOutStart for the resamplers are 1668 and 1770. And my buffer size is 256, so I prime this pipeline with 1668 + 256 + 1770 + 256 samples total.

After priming, this pipeline appears to be stable and can run continuously without slipping. There is always an available output buffer for each input buffer at the 48K end of the process. The 44.1K processing is obviously running at a different rate.  But, no buffer underruns or overruns occur.

This is exactly what I need! So why am I opening this issue? I am not sure this is by design or just luck. The results are only by experiment. I am opening this issue to ask if your library is expected to support a full-duplex scenario like this without extra code to deal with overflow/underflow conditions? Will this work for other conversion rates? Is there a risk of round-off errors that would cause the reverse conversion to yield more or less samples that the forward conversion?

I am attaching my test code here in case this helps.  As a side note, the output buffer length only varies by 277 samples min to max, and the buffer lengths cycle after 160 buffer conversions, which gives me more confidence it is stable indefinitely.  

`
   cout << "Running mono loopback re-sampler demo..." << endl;

    RingBuffer inboundBuffer(2048);
    RingBuffer outboundBuffer(2048);

    const int bufferSize = 256;

    CDSPResampler24 *inboundResampler = new CDSPResampler24(48000.0, 44100.0, bufferSize);
    int inboundBeforeStart = inboundResampler->getInLenBeforeOutStart();
    cout << "Inbound sample length before first output: " << inboundBeforeStart << endl;

    CDSPResampler24 *outboundResampler = new CDSPResampler24(44100.0, 48000.0, bufferSize);
    int outboundBeforeStart = outboundResampler->getInLenBeforeOutStart();
    cout << "Inbound sample length before first output: " << outboundBeforeStart << endl;

    double sampleRate = 48000.0;
    int inputSize = sampleRate * 30;
    double *input = createToneBuffer(sampleRate, inputSize);
    double *output = new double[inputSize + 4096];

    int inputPosition = 0;
    int outputPosition = 0;
    const int callbackBufferSize = 256;
    int primeLength = inboundBeforeStart + outboundBeforeStart + callbackBufferSize + callbackBufferSize;

    double loopbackBuffer[callbackBufferSize];

    std::ofstream ofs;
    ofs.open ("log.txt", std::ofstream::out | std::ofstream::app);

    int outboundBufferMin = 2048;
    int outboundBufferMax = 0;

    while (inputSize - inputPosition >= callbackBufferSize) {

        int inboundProcessCount = 0;
        int outboundProcessedCount = 0;

        double *inboundResampledBuffer;
        int inboundResampledLength = inboundResampler->process(input + inputPosition, callbackBufferSize, inboundResampledBuffer);

        if (inboundBuffer.writeCapacity() >= inboundResampledLength) {
            inboundBuffer.push(inboundResampledBuffer, inboundResampledLength);
        } else {
            cout << "Buffer overflow writing input position " << inputPosition << endl;
            return -1;
        }

        inboundProcessCount++;
        inputPosition += callbackBufferSize;

        while (inboundBuffer.readCapacity() >= callbackBufferSize) {

            inboundBuffer.pop(loopbackBuffer, callbackBufferSize);
            double *outboundResampledBuffer;
            int outboundResampledLength = outboundResampler->process(loopbackBuffer, callbackBufferSize, outboundResampledBuffer);
            outboundBuffer.push(outboundResampledBuffer, outboundResampledLength);
        }

        if (inputPosition > primeLength) {

            size_t readCapacity = outboundBuffer.readCapacity();
            outboundBufferMin = min(readCapacity, outboundBufferMin);
            outboundBufferMax = max(readCapacity, outboundBufferMax);

            if (readCapacity > callbackBufferSize) {

                outboundBuffer.pop(output + outputPosition, callbackBufferSize);
                outputPosition += callbackBufferSize;
                outboundProcessedCount++;
            } else {
                cout << "Buffer overflow reading output position " << outputPosition << endl;
            }
        }

        ofs << outboundBuffer.readCapacity() << " ";

    }

    ofs << endl;
    ofs.close();

    writeOutputFile(output, outputPosition, 48000.0, "duplex.wav");

    cout << ">>> Converted " << inputSize << " in to " << outputPosition << " out." << endl;
    cout << "outboundMin=" << outboundBufferMin << " outboundMax=" << outboundBufferMax << endl;
    cout << "Done." << endl;

`

**Comment by avaneev** [comment]
r8brain-free-src wasn't designed from ground-up for such use cases, but many users reported it works in such scenarios, for any sample rate combinations. If you buffer some minor output length variance, there should be no problems since sample timing of r8brain-free-src is extremely precise. Just make sure you are not setting R8B_FASTTIMING to 1.

**Comment by nadernader99** [comment]
That answers my question and is consistent with the results from my testing. Thank you for your reply.

**Comment by avaneev** [comment]
Generally speaking, some "jitter" you are afraid of MAY happen if samplerates differ by something like 0.0001%, due to loss of floating point precision. But since difference between standard sample rates is much larger, a drift of sample timing does not happen: I've tested the approach used in r8brain-free-src on trillion sample-to-sample advancements, and it never goes out of sync, and the integer sample position always advances as expected for the given samplerate conversion ratio.

**Comment by avaneev** [comment]
Well, there's one more thing: in such full-duplex scenario it's suggested to have some initial surplus input buffer data, at least ceil(DstSampleRate/SrcSampleRate*2), e.g. 5 samples if you are upsampling from 44100 to 96000 and then downsampling to 44100 since there will be frequent +/- 2 output length variations, but stable. When you downsample from 48000 to 44100 and then upsample back to 48000, no such variation happens, but initially it does happen - maybe you've not noticed it. Anyway, I would suggest buffering `ceil(DstSampleRate/SrcSampleRate*2)` samples in the input buffer to be on a safe side.

**Comment by avaneev** [comment]
FYI, r8brain-free-src now features the getInputRequiredForOutput() function which may be helpful for this kind of applications.
