### ISSUE TITLE
Some problems to deal with when adding a new vcpkg port of this project

### ISSUE THREAD

**Issue by CrSjimo** [avaneev/r8brain-free-src#29]
Hi, avaneev.

I am now working on adding a new vcpkg port of this project.

Since this project itself does not contain any build script, I wrote a [CMake script](https://github.com/microsoft/vcpkg/blob/56085ab2d4cc4380dc249711f95f4b66f6e1e5b1/ports/r8brain-free-src/CMakeLists.txt) to build the library. Now, there are still some problems to deal with. These problems are mentions in this pull request to vcpkg microsoft/vcpkg#42256.

1. What downstream users are expected to '#include' when using this library? For example, `#include <r8brain/CDSPResampler.h>`, or something else. Would you please give usage instructions on how the headers should be included?

2. Would you please check whether my CMake script builds the library correctly? Since no build instruction is provided, I am not very sure if my script builds the library in the expected way.

Also, it would be appreciated if you could join to help me with the pull request to vcpkg. 

BTW, I also strongly suggest that there should be official CMake support for this project since CMake is the de facto standard of C++ building and is used widely in most C++ projects. Without an official CMake script, the users have to write it on their own and might make some mistakes about it. (I have read closed issues and pull requests and knew you may not want to add CMake support, so whatever is OK)

**Comment by avaneev** [comment]
Sorry, I can't help with your CMake script - I'm not experienced with CMake. But for completeness you do need to support all macros described in the `r8bconf.h` file otherwise there's no much point in CMake support.

I do not know the way vcpkg user expect r8brain-free-src to be included, but I would name the folder as `r8brain-free-src`, because just `r8brain` is a name of a free desktop sample rate conversion tool, and there's also `r8brain PRO` tool available which is a different algorithm.

**Comment by avaneev** [comment]
The problem with "precompiling" is that if you compile r8brain-free-src with one set of R8B defines, and then include its headers with another set of R8B defines, the thing will break. This is due to header-only approach. That's the reason it's better to include compilation of object files on per-project basis, and not to resort to CMake. This, and the fact FFT libraries are not distributed under MIT licenses makes it hardly suitable for vcpkg I think. The developer has to consider FFT code licenses separately. They are allowed to be distributed with r8brain in source code form, but for binary distribution PFFFT requires explicit acknowledgment.

**Comment by CrSjimo** [comment]
> I do not know the way vcpkg user expect r8brain-free-src to be included, but I would name the folder as `r8brain-free-src`, because just `r8brain` is a name of a free desktop sample rate conversion tool, and there's also `r8brain PRO` tool available which is a different algorithm.

So, the users will `#include <r8brain-free-src/CDSPResampler.h>` to use this library. Is this what you expect?

**Comment by avaneev** [comment]
> So, the users will `#include <r8brain-free-src/CDSPResampler.h>` to use this library. Is this what you expect?

Yes, I assumed that.
