### ISSUE TITLE
Realtime latency tips

### ISSUE THREAD

**Issue by peterdk** [avaneev/r8brain-free-src#6]
I have been using this library for a few years in a quite popular Android piano app. Today I looked at this repo again and saw that a lot of work has been done. I tried the most recent version and it works even faster then before. So that's nice! 

I am optimizing my app for as low latency as possible, and was wondering what the best approach would be for this regarding the resampler?

In my current implementation I feed the resampler empty input data until the number of samples available in the output buffer is not 0 anymore. This is done once after the initialization of the resamplers. Is this a good approach? Or should I feed the actual input audio immediately? 

 ```
double * dummyInput = (double *) calloc(sizeof(double),channelLength);
for (int i = 0; i < channels; i++) {
    resamplers[i] = new r8b::CDSPResampler16((double) sampleRateIn, (double) sampleRateOut, channelLength);

    double * dummyOut;
    int processedCount = 0;
    while (processedCount == 0) {
	   processedCount = resamplers[i]->process(dummyInput, channelLength, dummyOut);
     }
}
free(dummyInput);
```
I am using PFFFT with NEON on ARM64: `#define R8B_PFFFT 1`

Thanks for this great library!

**Comment by avaneev** [comment]
I would try to feed the data immediately to reduce latency. Another possible way to reduce latency is to finetune the `ReqTransBand` parameter - by default it's 2.0, but 5.0 may be acceptable as well and this should reduce latency.

**Comment by avaneev** [comment]
What is your app name and URL? I would like to include it to the list of library users, if you do not mind.

**Comment by peterdk** [comment]
Ok, great. I will test with that.
What does the parameter do?

**Comment by peterdk** [comment]
The app is Mini Piano Lite and can be found at https://play.google.com/store/apps/details?id=umito.android.minipiano

**Comment by peterdk** [comment]
I have several resampling needs. I assume that for resampling from 22050 to 44100 it automatically uses a faster path due to it being 2x? Or do I need to specify a different resampler?

**Comment by avaneev** [comment]
Yes, it will use the fastest path in any sample rate combinations. All latest changes I've implemented I think assure that. No idea how it can be optimized further.

**Comment by avaneev** [comment]
The `ReqTransBand` controls filter's transition band. For 22050 to 44100 conversion 2.0 means that frequencies beyond 10800 Hz are attenuated, 5.0 means that frequencies beyond 10473.75 are attenuated - not a big difference, but provides a bit lower latency.

**Comment by peterdk** [comment]
Ok, can I also use that for 44100 -> 48000 ? Or should I use the default there?

**Comment by avaneev** [comment]
Yes, you can, for 44100 -> 48000 conversion you can use even 8.0 without audible issues. 2.0 is mostly for professional "no regrets" use.

**Comment by peterdk** [comment]
Ok, thanks! It really is helpful.

I have one final question, is it possible using r8brain to like frequency shift the input? For example, I have a wav file with a note on 443 hz, but want it to transpose to 440hz? In FFMPEG I can do this using samplerate options, so was wondering if I can do it dynamically as well.

**Comment by avaneev** [comment]
r8brain-free-src has no time-preserving frequency shifting, but you can do any frequency shifts that are non-time preserving.

**Comment by peterdk** [comment]
Ok, thank you very much for the info!

**Comment by tdchao29** [comment]
Hi @avaneev ,

First off, thanks for creating this library, it looks great.

Building off @peterdk 's initial comment, I observed the same phenomenon using r8b::CDSPResampler16, in which the number of output samples returned by the first few calls to process() is zero. Like you advised, I am trying to feed the data in immediately, rather than employ the suggested idea of feeding in a dummy buffer. However, the return value of zero is still a problem for me because when my program nears the end of its execution, it expects a certain number of samples to already have been written overall. The zeroes cause this number to be off, which leads to data length "accounting" issues, so to speak. Consider the pseudocode from your sample program example.cpp:

	long long int ol = inf.SampleCount * OutSampleRate / inf.SampleRate;

	while( ol > 0 )
	{
		...
		// WriteCount := process() return value
		...
		ol -= WriteCount;
	}

I'm modeling my code after this and I essentially get an infinite loop because of those iterations that are setting WriteCount to zero instead of the expected number of samples written. Furthermore, input data is still getting consumed on these "zero" iterations, and I fear it is getting lost.

Like @peterdk , I've actually managed to find a couple of ways around this and I'm happy with the resulting audio when I apply my fix. But I still wanted to ping the author and ask if there is, perhaps, an explanation for process() returning zeroes in the first place (is this all expected?), and if there is a recommended way I should deal with this. Please also let me know if you'd like me to share how I am currently handling this issue.

Thank you!

**Comment by avaneev** [comment]
Digital filters have an inherent delay, which is absorbed by the algorithm and thus initially it may return zeros. You've omitted a part in `example.cpp` which feeds zero input to the resampler when the input data ends. This is the solution to your problem.

**Comment by tdchao29** [comment]
I see, thanks for the explanation. How about when the input data begins? Is the input data not consumed and lost during the short period of time that process() is returning zero?

**Comment by avaneev** [comment]
No, the input data is not lost - it is accumulated in internal buffers.

**Comment by tdchao29** [comment]
Thanks!
